### ISSUE TITLE
Analyzer instances can't be created

### ISSUE THREAD

**Issue by onovotny** [xunit/xunit#1307]
When I try to use the analyzers in an SDK project targeting .NET 4.6 and netcoreapp1.1, I see the following warnings in the output window. This is with the `0.3.0` package on NuGet.org.

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8032	An instance of analyzer Xunit.Analyzers.TheoryMethodCannotHaveParamsArray cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.TheoryMethodCannotHaveParamsArray' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(netcoreapp1.1)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertEqualGenericShouldNotBeUsedForStringValue cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertEqualGenericShouldNotBeUsedForStringValue' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(net46)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertEqualGenericShouldNotBeUsedForStringValue cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertEqualGenericShouldNotBeUsedForStringValue' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(netcoreapp1.1)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertIsTypeShouldUseGenericOverloadType cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertIsTypeShouldUseGenericOverloadType' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(net46)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertIsTypeShouldUseGenericOverloadType cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertIsTypeShouldUseGenericOverloadType' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(netcoreapp1.1)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertRegexMatchShouldNotUseBoolLiteralCheck cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertRegexMatchShouldNotUseBoolLiteralCheck' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(net46)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertRegexMatchShouldNotUseBoolLiteralCheck cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertRegexMatchShouldNotUseBoolLiteralCheck' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(netcoreapp1.1)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertSameShouldNotBeCalledOnValueTypes cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertSameShouldNotBeCalledOnValueTypes' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(net46)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertSameShouldNotBeCalledOnValueTypes cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertSameShouldNotBeCalledOnValueTypes' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(netcoreapp1.1)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertStringEqualityCheckShouldNotUseBoolCheck cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertStringEqualityCheckShouldNotUseBoolCheck' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(net46)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertStringEqualityCheckShouldNotUseBoolCheck cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertStringEqualityCheckShouldNotUseBoolCheck' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(netcoreapp1.1)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertSubstringCheckShouldNotUseBoolCheck cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertSubstringCheckShouldNotUseBoolCheck' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(net46)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.AssertSubstringCheckShouldNotUseBoolCheck cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.AssertSubstringCheckShouldNotUseBoolCheck' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(netcoreapp1.1)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.MemberDataShouldReferenceValidMember cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.MemberDataShouldReferenceValidMember' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(net46)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.MemberDataShouldReferenceValidMember cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.MemberDataShouldReferenceValidMember' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(netcoreapp1.1)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.TestMethodCannotHaveOverloads cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.TestMethodCannotHaveOverloads' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(net46)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.TestMethodCannotHaveOverloads cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.TestMethodCannotHaveOverloads' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(netcoreapp1.1)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.TheoryMethodCannotHaveDefaultParameter cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.TheoryMethodCannotHaveDefaultParameter' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(net46)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.TheoryMethodCannotHaveDefaultParameter cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.TheoryMethodCannotHaveDefaultParameter' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(netcoreapp1.1)		1	Active
Warning	CS8032	An instance of analyzer Xunit.Analyzers.TheoryMethodCannotHaveParamsArray cannot be created from C:\Users\oren\.nuget\packages\xunit.analyzers\0.3.0\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.TheoryMethodCannotHaveParamsArray' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	Humanizer.Tests(net46)		1	Active
```

**Comment by bradwilson** [comment]
The 0.1.0 version numbers seem like a giveaway. Did you restart Visual Studio after doing the upgrade?

**Comment by onovotny** [comment]
It wasn't an upgrade, I don't think...I just added it. Was the 0.1 version chained in by the beta package separately?

**Comment by onovotny** [comment]
And after restarting VS, I'm not seeing that, so wonderful :/

**Comment by onovotny** [comment]
Okay, so there's a caching issue with analyzers :(

**Comment by onovotny** [comment]
Do you know if there's an issue tracking this?

**Comment by bradwilson** [comment]
No idea.

**Comment by marcind** [comment]
Looks like there's nothing that we can do here, closing.

**Comment by natemcmaster** [comment]
I ran into this too.  I couldn't find an issue tracking this so I've opened https://github.com/dotnet/project-system/issues/2719.

**Comment by memark** [comment]
Did you find a workaround? Can the cache be cleaned? Or is it eventually timing out? @onovotny @natemcmaster

**Comment by natemcmaster** [comment]
@memark restart VS. That's the only workaround I'm aware of.

**Comment by BrianKrohn** [comment]
I get this building on the cmd line with msbuild. Restart VS not an option, so I how do I work around?

**Comment by marcind** [comment]
@BrianKrohn Nobody has encountered this issue on the command line yet. Could this be some caching issue inside the msbuild process? Have you tried killing all instances of msbuild.exe? (they'll also shut down on their own after some period of time)

**Comment by nlivaic** [comment]
I've had a similar issue when building on the build server. 
Locally everything works fine even though I have no references to Microsoft.CodeAnalysis.dll in my project, nor is it in my GAC.

`CSC error CS8032: An instance of analyzer Xunit.Analyzers.TheoryMethodMustHaveTestData cannot be created from E:\DEV-AGENT03\work\preview\packages\xunit.analyzers.0.10.0\analyzers\dotnet\cs\xunit.analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..`

**Comment by jakubsuchybio** [comment]
Just got that issue when upgrading from xunit 2.4.1 to 2.5.0, I'm using Rider and I tried to restart rider (with killing all msbuild processes), but it didn't work 😭, any other suggestions?
I tried to clean clone the repo
I tried to delete <user>/.nuget folder
Nothing works 😭

**Comment by bradwilson** [comment]
@jakubsuchybio I would open an issue with Rider, as the analyzers are working fine in VS 2022 and with command line builds.

**Comment by Michal-Niesluchowski** [comment]
I have the same issue on Microsoft TFS. After upgrading xunit from 2.4.1 to 2.5.0 TFS builder throws the discussed errors. Locally on VS22 and VS19 works just fine. The only solution that I found was to revert to 2.4.1. However I'm no DevOps. Clearly not xunit error but environment specific, but just wanted to comment for the legasy sake.
