### ISSUE TITLE
Assert.ThrowsAsync<T> is ambiguous between Task en ValueTask

### ISSUE THREAD

**Issue by erdtsieck** [xunit/xunit#2808]
<img width="894" alt="image" src="https://github.com/xunit/xunit/assets/1730868/4adad1a4-14fb-4b9a-b9b5-78abcafe9033">

```csharp
await Assert.ThrowsAsync<ScenarioAssertionException>(async () =>
{
    await FooAsync();
});
```

Gives the error: 

> The call is ambiguous between the following methods or properties: 'Assert.ThrowsAsync&lt;T&gt;(Func&lt;Task&gt;)' and 'Assert.ThrowsAsync&lt;T&gt;(Func&lt;ValueTask&gt;)'

**Comment by bgrainger** [comment]
Here's a simple repro:

```csharp
using Xunit;

namespace XUnitTest;

public class TestClass1
{
    public Task AsyncMethod() => Task.FromException(new Exception());
}

public class UnitTest1
{
    [Fact]
    public async Task Test1()
    {
        await Assert.ThrowsAsync<Exception>(async () => await new TestClass1().AsyncMethod());
    }
}
```

This test works fine with xunit 2.5.3 but with xunit 2.6.0, `dotnet build` generates `UnitTest1.cs(17,22): error CS0121: The call is ambiguous between the following methods or properties: 'Assert.ThrowsAsync<T>(Func<Task>)' and 'Assert.ThrowsAsync<T>(Func<ValueTask>)`.

**Comment by ALars3n** [comment]
You could define the task as an variable and pass it to the assertion. The return type then needs to be explicitly defined. 

```
using Xunit;

namespace XUnitTest;

public class TestClass1
{
    public Task AsyncMethod() => Task.FromException(new Exception());
}

public class UnitTest1
{
    [Fact]
    public async Task Test1()
    {
        Func<ValueTask> task = async () => await new TestClass1().AsyncMethod();
        await Assert.ThrowsAsync<Exception>(task);
    }
}
```

Not the best approach but I don't see an alternative way.

**Comment by bradwilson** [comment]
The only way to solve this (because it's a compiler ambiguity) would be to have different names for the overloads. I considered both and landed on the "same name" policy because it felt like it had better discoverability.

Honestly, this feels like something the compiler _could_ choose to fix, since it's the one that's not only matching the method but generating the signature of the lambda. So maybe someone should open that as a bug against the C# compiler. 😄

**Comment by bradwilson** [comment]
I'm going to label this as External for the moment and see what the Roslyn team thinks.

**Comment by bradwilson** [comment]
If I end up renaming functions, I'm considering doing something that might feel a little user hostile, but for good reason, so I'm going to propose two possible solutions here to see what people think (and give people a chance to come up with another alternative.

Personally, I highly prefer Option B. I believe Option A leaves us with signatures people will likely never see, and not realize it's legal to use `ValueTask`.

### Option A

1. Remove `Assert.Throws*` overloads that take `ValueTask`
2. Add `Assert.Throws*ValueTask` overloads that take `ValueTask`

### Option B

1. Mark `Assert.Throws*` overloads as `[Obsolete]` with a message about using one of the new signatures
3. Add `Assert.Throws*Task<T>` overloads for `Task` variants
4. Add `Assert.Throws*ValueTask<T>` overloads for `ValueTask` variants

**Comment by bradwilson** [comment]
The Roslyn just closed the issue and recommends not supporting `ValueTask` at all, so let's call that:

### Option C

1. Remove `Assert.Throws*` overloads that take `ValueTask`
2. (There is no Step 2. Just stop supporting `ValueTask`.)

**Comment by MarcusChr** [comment]
> You could define the task as an variable and pass it to the assertion. The return type then needs to be explicitly defined.
> 
> ```
> using Xunit;
> 
> namespace XUnitTest;
> 
> public class TestClass1
> {
>     public Task AsyncMethod() => Task.FromException(new Exception());
> }
> 
> public class UnitTest1
> {
>     [Fact]
>     public async Task Test1()
>     {
>         Func<ValueTask> task = async () => await new TestClass1().AsyncMethod();
>         await Assert.ThrowsAsync<Exception>(task);
>     }
> }
> ```
> 
> Not the best approach but I don't see an alternative way.

Alternatively, you could cast the async delegate to either `Func<Task>` or `Func<ValueTask>`:
![billede](https://github.com/xunit/xunit/assets/39948553/3122d618-eaf7-4731-b85a-c2ee0000aeaa)

**Comment by bradwilson** [comment]
I have prototyped a complete removal of `ValueTask` support (and removal of `XUNIT_VALUETASK`, which should no longer be necessary).

This includes conversions (for net-new async assertions which are currently `ValueTask` only):

- `Assert.AllAsync<T>(IEnumerable<T>, Func<T, ValueTask>)` to
   `Assert.AllAsync<T>(IEnumerable<T>, Func<T, Task>)`
- `Assert.CollectionAsync<T>(IEnumerable<T>, params Func<T, ValueTask>[])` to
   `Assert.CollectionAsync<T>(IEnumerable<T>, params Func<T, Task>[])`

And removals (for new async overloads):

- `Assert.PropertyChangedAsync(INotifyPropertyChanged, string, Func<ValueTask>)`
- `Assert.RaisesAnyAsync(Action<EventHandler>, Action<EventHandler>, Func<ValueTask>)`
- `Assert.RaisesAnyAsync<T>(Action<EventHandler<T>>, Action<EventHandler<T>>, Func<ValueTask>)`
- `Assert.RaisesAsync<T>(Action<EventHandler<T>>, Action<EventHandler<T>>, Func<ValueTask>)`
- `Assert.Throws<T>(string?, Func<ValueTask>)`
- `Assert.ThrowsAnyAsync<T>(Func<ValueTask>)`
- `Assert.ThrowsAsync(Type, Func<ValueTask>)`
- `Assert.ThrowsAsync<T>(Func<ValueTask>)`
- `Assert.ThrowsAsync<T>(string?, Func<ValueTask>)`

As expected, a few tests had to be updated to add `.AsTask()` on the end of them, because the function in question was returning `ValueTask` instead of `Task`. In my case, they were all non-async lambdas, so my choice to convert:

```csharp
await Assert.ThrowsAsync<Type>(() => ValueTaskReturningThing());
```

Included two options:

```csharp
// Use .AsTask()
await Assert.ThrowsAsync<Type>(() => ValueTaskReturningThing().AsTask());

// Use async
await Assert.ThrowsAsync<Type>(async () => await ValueTaskReturningThing());
```

I suspect a relatively low number of people were using lambdas the way that I do (my brain just won't let me force the creation of the async machinery when it's not necessary 😂).

**Comment by gimlichael** [comment]
Just updated to latest and greatest - immediately rewarded with 61 errors. Should I interpret your last comment as you will remove the overloaded support for ValueTask? If so, I will in the meantime roll-back to 2.5.3, and hopefully update to 2.6.1 soon-to-be :-)

Thanks.

**Comment by bradwilson** [comment]
For the prototype removal...

Assertion changes: https://github.com/xunit/assert.xunit/commit/5986aa7bfa07ec3ad07043e4f717ef1eb01103aa?w=1
Core framework changes: https://github.com/xunit/xunit/commit/bcff04cdb38a22db793003eafe8c19dc19b2c423?w=1

**Comment by bradwilson** [comment]
@gimlichael

> Should I interpret your last comment as you will remove the overloaded support for ValueTask?

That is one of three proposals, but regardless of which one wins, the intent is to remove the ambiguity.

**Comment by trejjam** [comment]
I think since c# 11 you can  write
```cs
public class UnitTest1
{
    [Fact]
    public async Task Test1()
    {
        await Assert.ThrowsAsync<Exception>(async Task () => await new TestClass1().AsyncMethod());
    }

    [Fact]
    public async Task Test2()
    {
        await Assert.ThrowsAsync<Exception>(async ValueTask () => await new TestClass1().AsyncMethod());
    }
}
```,
which resolves the ambiguity

**Comment by bradwilson** [comment]
@trejjam Yeah, but:

- You still get the friction of the ambiguity error
- You have to know that syntax could fix it (since CS0121 isn't going to tell you)
- You have to be using C# 11 to fix it

**Comment by gimlichael** [comment]
> I think since c# 11 you can write
> 
> ```cs
> public class UnitTest1
> {
>     [Fact]
>     public async Task Test1()
>     {
>         await Assert.ThrowsAsync<Exception>(async Task () => await new TestClass1().AsyncMethod());
>     }
> 
>     [Fact]
>     public async Task Test2()
>     {
>         await Assert.ThrowsAsync<Exception>(async ValueTask () => await new TestClass1().AsyncMethod());
>     }
> }
> ```
> 
> which resolves the ambiguity

This could work and the effort is neglectable .. however, I do believe the overall developer experience is impacted and the organic CPU will take a spin or two. My vote goes to remove the ValueTask overload in its current state.

**Comment by bradwilson** [comment]
I prototyped the other two options and I think at the end, just removing `ValueTask` is best. It'll even end up adding two new assertions to people who aren't on .NET 6 yet (`Assert.AllAsync` and `Assert.CollectionAsync`).

**Comment by bradwilson** [comment]
### Commits

Assertions: https://github.com/xunit/assert.xunit/commit/5986aa7bfa07ec3ad07043e4f717ef1eb01103aa?w=1
v2 (tests): https://github.com/xunit/xunit/commit/fb3c3cf30445dc5a7aa7fdca6fe8118dc407b960?w=1
v3 (tests): https://github.com/xunit/xunit/commit/eb580243be481d1ce82ada0bf0283a5532e2b6af?w=1

### Builds

Available in v2 `2.6.1-pre.5`
Available in v3 `0.1.1-pre.312`

**Comment by bradwilson** [comment]
@RyanGaudion The CI build is usable right now: https://xunit.net/docs/using-ci-builds

It's my intention to cut final `2.6.1` today. Just looking at one more open analyzers PR to bundle it all together.

**Comment by 0xced** [comment]
I'm a bit late to the party, but for what it's worth, FluentAssertions also chose to not support `ValueTask`. In https://github.com/fluentassertions/fluentassertions/issues/1763 it's recommended to use `.AsTask()`.

**Comment by bradwilson** [comment]
2.6.1 RTM is on NuGet now. Release notes: https://xunit.net/releases/v2/2.6.1

https://dotnet.social/@xunit/111342661395230711

![image](https://github.com/xunit/xunit/assets/16944/6d5708ad-2669-4c7c-8a82-699a4359a3d5)

**Comment by AnthonyMastrean** [comment]
The same issue exists in the `Record` class.

https://github.com/xunit/xunit/blob/v3-1.0.1/src/xunit.v3.core/Record.cs

**Comment by bradwilson** [comment]
@AnthonyMastrean Thanks, not sure how I missed that. 🤦🏼

The fix is available in v3 `2.0.0-pre.9` https://xunit.net/docs/using-ci-builds

**Comment by Pentadome** [comment]
Maybe [OverloadResolutionPriority](https://learn.microsoft.com/en-us/dotnet/api/System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute.-ctor?view=net-9.0) could be useful here?

```csharp
public class Test
{
    [OverloadResolutionPriority(1)]
    public static async Task Test(Func<ValueTask> func)
    {
        await func();
    }
    
    
    public static async Task Test(Func<Task> func)
    {
        await func();
    }

    public static async Task Exec()
    {
        await Test(async () =>
        {
            await Task.CompletedTask;
        });
    }
}
```

**Comment by bradwilson** [comment]
> Maybe [OverloadResolutionPriority](https://learn.microsoft.com/en-us/dotnet/api/System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute.-ctor?view=net-9.0) could be useful here?

We could polyfill that but even so, it would only be effective for people using .NET 9 SDK.

It's better to just remove the ambiguity as it's unnecessary.
