### ISSUE TITLE
E0308 on Assert::Throws<Exception^>(action);

### ISSUE THREAD

**Issue by cpuwzd** [xunit/xunit#2364]
Before you file a bug...

* Is this a question?
  Ask it on our discussion area: https://github.com/xunit/xunit/discussions
* Is this a bug with VSTest (aka Visual Studio Test Explorer, `dotnet test`, `dotnet vstest`,
  or `vstest.console.exe`)? Open those issues here:
  https://github.com/xunit/visualstudio.xunit/issues/
* Did you search the docs @ https://xunit.net/ ?
* Did you search the issues list to see if someone already reported it?
  When looking for duplicates, make sure to look through open **and** closed issues.
* Did you create a simple repro for the problem?
  Bugs without repro projects will be automatically closed.

This appears to be a design bug. I'm working on the Wix4.0 project and  I'm running VS2019. In particular, the DUtilUnitTest.
DUtilTraceErrorSourceFiltersOnTraceLevel reports a compilation error on the second line of the following code:

```C++
            Action^ action = gcnew Action(this, &DUtil::CallDutilTraceErrorSource);
            Assert::Throws<Exception^>(action);
```

The error is E0308: more than one instance of overloaded function `Xunit::Assert::Throws` matches the argument list.

This is confirmed by the Object Browser, which shows that, because the argument is both an Action^ and an Object^,
two overloads are destined to overlap. I don't know any way to force the resolution, but my C++ is a little rusty.

**Comment by bartelink** [comment]
Same happens in F#; you need to disambiguate at the call site in some cases - 'fixing' that would be a breaking change.

Either way, best to close this issue and use StackOverflow to figure out the cleanest resolution.

**Comment by bradwilson** [comment]
Agreed, I don't think there's anything we can do about this, as it's a language issue in C++ rather than an issue with our library. We provide both these overloads (one which takes `Action` and one with takes `Func<object>`) so that calling code can be tested which expects to throw exceptions, regardless of whether the code returns a value (`Func<object>`) or not (`Action`).
